version: '3'

services:
  flask-api:
    build: .
    container_name: email-spam-api
    environment:
      - PORT=5001
      - GOOGLE_APPLICATION_CREDENTIALS=/app/gcp-credentials.json
    ports:
      - "5001:5001"
    volumes:
      - ./gcp-credentials.json:/app/gcp-credentials.json:ro